/**
 * opencode-vision-bridge
 *
 * Gives vision to non-vision models in OpenCode by transparently replacing
 * image parts with detailed text descriptions generated by Google's free
 * Gemini API. Vision-capable models are left untouched and keep seeing the
 * raw image.
 *
 * Zero runtime dependencies. Loaded either from a global/project plugin
 * directory (auto-discovered) or from npm via the `plugin` config array.
 *
 * @module
 */

import { readFile } from "node:fs/promises"
import { existsSync } from "node:fs"
import { fileURLToPath, pathToFileURL } from "node:url"
import { isAbsolute, resolve } from "node:path"
import { createHash } from "node:crypto"

/**
 * Provider patterns that ship vision-capable models. Requests to these
 * models are never transformed unless explicitly included.
 *
 * @type {string[]}
 */
export const DEFAULT_EXCLUDE_MODELS = [
  "anthropic/.*",
  "openai/gpt-4o.*",
  "openai/gpt-5.*",
  "openai/o3.*",
  "openai/o4.*",
  "google/gemini.*",
  "xai/.*",
  "mistral/pixtral.*",
  "groq/llama-4.*",
]

/**
 * Default system-style prompt sent to Gemini alongside the image. It asks
 * for a factual, exhaustive description — including verbatim transcription
 * of any text in the image — because the description is the only "eyes" the
 * target model has.
 *
 * @type {string}
 */
export const DEFAULT_DESCRIBE_PROMPT = `You are an image description service. A text-only LLM cannot see this image, so your description is its only eyes. Describe the image in complete detail:
1. Overall layout and structure
2. ALL text in the image, transcribed verbatim (UI labels, error messages, code, terminal output, document text)
3. UI elements: buttons, menus, icons, their state (active/disabled/error)
4. Colors, visual style, and anything visually notable
5. Any anomalies, errors, or warnings visible
Be exhaustive and factual. Do not interpret, just describe what is visually present. If it is a screenshot, this is the MOST important case: transcribe every piece of text exactly.`

/**
 * Plugin options. All fields are optional; environment variables are used
 * as fallbacks when an option is not provided.
 *
 * @typedef {Object} VisionBridgeOptions
 * @property {string} [apiKey]            Gemini API key. Fallback: `VISION_BRIDGE_API_KEY`, `GEMINI_API_KEY`, `GOOGLE_API_KEY`.
 * @property {string} [geminiModel]       Gemini model id. Fallback: `VISION_BRIDGE_MODEL` or `"gemini-2.5-flash"`.
 * @property {string[]} [includeModels]   Regexes matching `provider/model` to ALWAYS transform (overrides exclusions).
 * @property {string[]} [excludeModels]   Regexes matching `provider/model` to NEVER transform. Defaults to `DEFAULT_EXCLUDE_MODELS` plus `VISION_BRIDGE_EXCLUDE`.
 * @property {string} [prompt]            Custom description prompt sent to Gemini.
 */

const API_BASE = "https://generativelanguage.googleapis.com/v1beta/models"

/** @param {string} pattern @returns {RegExp} */
const toRegExp = (pattern) => new RegExp(pattern)

/**
 * Decide whether a request for the given model should have its image parts
 * transformed into text descriptions.
 *
 * @param {string|undefined} modelID
 * @param {string|undefined} providerID
 * @param {{ includeModels?: string[], excludeModels?: string[] }} opts
 * @returns {boolean}
 */
export function shouldTransform(modelID, providerID, opts = {}) {
  if (!modelID || !providerID) return false
  const full = `${providerID}/${modelID}`
  const include = opts.includeModels ?? []
  const exclude = opts.excludeModels ?? DEFAULT_EXCLUDE_MODELS
  if (include.length > 0) return include.some((p) => toRegExp(p).test(full))
  return !exclude.some((p) => toRegExp(p).test(full))
}

/**
 * Parse a base64 data URI.
 *
 * @param {string} url
 * @returns {{ mime: string, data: string } | null} mime type and base64 payload
 */
export function parseDataUri(url) {
  const match = /^data:([^;,]+)?;base64,(.*)$/s.exec(url)
  if (!match) return null
  return { mime: match[1] || "image/png", data: match[2] }
}

/**
 * Resolve a part URL to a local filesystem path. Accepts `file://` URLs,
 * `pathToFileURL` output, and plain absolute/relative paths.
 *
 * @param {string} url
 * @returns {string | null}
 */
export function resolveFilePath(url) {
  let path = url
  if (path.startsWith("file://")) {
    try {
      path = fileURLToPath(path)
    } catch {
      return null
    }
  }
  if (!isAbsolute(path)) path = resolve(path)
  return path
}

/**
 * Read an image part into a { mime, data } payload usable as Gemini
 * `inline_data`. Handles data URIs and local file references.
 *
 * @param {{ url?: string, mime?: string }} part
 * @returns {Promise<{ mime: string, data: string } | null>}
 */
export async function loadImage(part) {
  const url = part.url || ""
  const parsed = parseDataUri(url)
  if (parsed) return { mime: part.mime || parsed.mime, data: parsed.data }

  const path = resolveFilePath(url)
  if (!path || !existsSync(path)) return null
  try {
    const buf = await readFile(path)
    return { mime: part.mime || "image/png", data: buf.toString("base64") }
  } catch {
    return null
  }
}

/**
 * Stable cache key for a set of images. Based on a hash of the payloads so
 * repeated or identical images reuse a previous description without a new
 * API call, while different images never collide.
 *
 * @param {{ mime: string, data: string }[]} images
 * @returns {string}
 */
export function cacheKey(images) {
  return images
    .map((i) => createHash("sha1").update(`${i.mime}\0${i.data}`).digest("hex").slice(0, 16))
    .sort()
    .join("|")
}

/**
 * Call Gemini's `generateContent` with a small retry/backoff loop for
 * transient failures (429 rate limits, 5xx).
 *
 * @param {{ mime: string, data: string }[]} images
 * @param {string} key
 * @param {string} model
 * @param {string} prompt
 * @param {Function} log
 * @param {{ set?: (k: string, v: string) => void, get?: (k: string) => string | undefined }|undefined} cache
 * @returns {Promise<string | undefined>}
 */
export async function describeImages(images, { key, model, prompt, log = () => {}, cache }) {
  const ck = cacheKey(images)
  if (cache?.get) {
    const hit = cache.get(ck)
    if (hit) return hit
  }

  let response
  for (let attempt = 0; attempt < 4; attempt++) {
    response = await fetch(
      `${API_BASE}/${encodeURIComponent(model)}:generateContent?key=${encodeURIComponent(key)}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          contents: [
            {
              role: "user",
              parts: [
                ...images.map((i) => ({ inline_data: { mime_type: i.mime, data: i.data } })),
                { text: prompt },
              ],
            },
          ],
          generationConfig: { temperature: 0.2, maxOutputTokens: 4096 },
        }),
      }
    )
    if (response.ok || (response.status !== 429 && response.status < 500)) break
    await new Promise((r) => setTimeout(r, 1000 * 2 ** attempt))
  }

  if (!response || !response.ok) {
    const status = response?.status ?? "no-response"
    const bodyText = await response?.text().catch(() => "")
    log("error", `Gemini request failed (${status}): ${bodyText}`)
    return undefined
  }

  const body = await response.json()
  const text = body?.candidates?.[0]?.content?.parts
    ?.map((p) => p.text)
    .join("")
    .trim()
  if (!text) {
    log("error", "Gemini returned an empty description")
    return undefined
  }
  cache?.set?.(ck, text)
  return text
}

/**
 * OpenCode plugin entry point.
 *
 * @param {import("@opencode-ai/plugin").PluginInput} ctx
 * @param {VisionBridgeOptions} [rawOptions]
 * @returns {Promise<import("@opencode-ai/plugin").Hooks>}
 */
export const VisionBridge = async (ctx, rawOptions = {}) => {
  const key =
    rawOptions.apiKey ||
    process.env.VISION_BRIDGE_API_KEY ||
    process.env.GEMINI_API_KEY ||
    process.env.GOOGLE_API_KEY
  const geminiModel = rawOptions.geminiModel || process.env.VISION_BRIDGE_MODEL || "gemini-2.5-flash"
  const includeModels =
    rawOptions.includeModels ||
    (process.env.VISION_BRIDGE_INCLUDE || "").split(",").map((s) => s.trim()).filter(Boolean)
  const excludeModels = [
    ...(rawOptions.excludeModels ?? DEFAULT_EXCLUDE_MODELS),
    ...(process.env.VISION_BRIDGE_EXCLUDE || "").split(",").map((s) => s.trim()).filter(Boolean),
  ]
  const prompt = rawOptions.prompt || DEFAULT_DESCRIBE_PROMPT
  const cache = new Map()

  const log = (level, message) => {
    try {
      ctx.client.app.log({ body: { service: "opencode-vision-bridge", level, message } })
    } catch {
      console.error(`[opencode-vision-bridge] ${level}: ${message}`)
    }
  }

  if (!key) {
    log("warn", "No Gemini API key found. Set GEMINI_API_KEY (or VISION_BRIDGE_API_KEY). Image parts will pass through untransformed.")
  }

  return {
    /**
     * Transform outgoing request messages: replace image parts with Gemini
     * text descriptions for models that cannot see images.
     */
    "experimental.chat.messages.transform": async (_input, output) => {
      if (!key) return
      for (const message of output.messages) {
        const info = message.info
        if (!shouldTransform(info?.model?.modelID, info?.model?.providerID, { includeModels, excludeModels })) {
          continue
        }
        const imageParts = message.parts.filter(
          (p) => p.type === "file" && typeof p.mime === "string" && p.mime.startsWith("image/")
        )
        if (imageParts.length === 0) continue

        const images = []
        for (const part of imageParts) {
          const loaded = await loadImage(part)
          if (loaded) images.push(loaded)
        }
        if (images.length === 0) continue

        log("debug", `Describing ${images.length} image(s) for ${info?.model?.providerID}/${info?.model?.modelID} via ${geminiModel}`)
        const description = await describeImages(images, { key, model: geminiModel, prompt, log, cache })
        if (!description) continue

        const first = imageParts[0]
        const replacement = {
          id: first.id,
          sessionID: first.sessionID,
          messageID: first.messageID,
          type: "text",
          text: `[Image description (generated by opencode-vision-bridge via ${geminiModel})]\n${description}`,
        }
        message.parts = [replacement, ...message.parts.filter((p) => !imageParts.includes(p))]
      }
    },
  }
}

export default VisionBridge
